spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    database: 9
    #    password:
    lettuce:
      pool:
        min-idle: 8
        max-idle: 16
        max-active: 1000
        max-wait: 3000