spring:
  datasource:
    url: jdbc:mysql://10.3.72.135:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: Abc#123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  redis:
    host: 10.3.69.41
  kafka:     # 指定kafka 代理地址，可以多个
    bootstrap-servers: 10.206.32.8:9092

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE