spring:
  redis:
    host: 10.3.69.41
    port: 6379
    timeout: 3000
    password: vPmUKab7ME
    database: 9
    lettuce:
      pool:
        min-idle: 8
        max-idle: 16
        max-active: 1000
        max-wait: 3000
